# 관리자 권한 여부
sudo: required

# 언어(플랫폼 선택)
language: generic

# 도커 환경 구성
services:
  - docker

# 스크립트를 실행할 수 있는 환경 구성
before_install:
  - echo "start C7reating an image with dockerfile"
  - docker build -t desfox/docker-react-app -f Dockerfile.dev .

# 실행할 스크립트(테스트 실행)
script:
  -docker run -e CI=true desfox/docker-react-app npm run test -- --coverage

# 테스트 성공 후 할 일
after_success:
  - echo "Test Success"